SELECT		emp.EMPLOYEE_ID AS EIN
			, emp.SURNAME+', '+emp.FIRST_NAME AS NAME
			, emp.EMP_GROUP_CODE
			, grp.DESCRIPTION_ABBR
			, emp.HOME_LOCATION_CODE
			, loc.DESCRIPTION_ABBR
			, emp.CONTRACT_CODE
			, cnt.DESCRIPTION_ABBR
			, emp.CONTRACT_DATE
			, emp.ORIGINAL_START_DATE
			, emp.REVIEW_DATE
			, emp.TERMINATION_CODE 
			, t.DESCRIPTION_ABBR
			, emp.TERMINATION_DATE
			, emp.PREVIOUS_TERMINATION_CODE
			, pt.DESCRIPTION_ABBR
			, emp.PREVIOUS_TERMINATION_DATE
FROM		EC_EMPLOYEE emp
JOIN		EC_GROUP_CODES grp			ON  grp.EMP_GROUP_CODE = emp.EMP_GROUP_CODE
JOIN		EC_LOCATIONS loc			ON	loc.LOCATION_CODE = emp.HOME_LOCATION_CODE
LEFT JOIN   EC_CODE_CONTRACT_CODE cnt	ON	cnt.CODE_VALUE = emp.CONTRACT_CODE
LEFT JOIN	EC_CODE_TERMINATION_CODE t	ON	t.CODE_VALUE = emp.TERMINATION_CODE
LEFT JOIN	EC_CODE_TERMINATION_CODE pt	ON	pt.CODE_VALUE = emp.PREVIOUS_TERMINATION_CODE



