SELECT		EMPLOYEE_ID
			, SURNAME
			, FIRST_NAME
			, emp.EMP_GROUP_CODE
			, grp.DESCRIPTION_ABBR
			, HOME_LOCATION_CODE
			, loc.DESCRIPTION_ABBR
			, CONTRACT_CODE
			, cnt.DESCRIPTION_ABBR
			, CONTRACT_DATE
			, ORIGINAL_START_DATE
			, REVIEW_DATE
			, TERMINATION_CODE 
			, t.DESCRIPTION_ABBR
			, TERMINATION_DATE
			, PREVIOUS_TERMINATION_CODE
			, pt.DESCRIPTION_ABBR
			, PREVIOUS_TERMINATION_DATE
FROM		EC_EMPLOYEE emp
JOIN		EC_GROUP_CODES grp			ON  grp.EMP_GROUP_CODE = emp.EMP_GROUP_CODE
JOIN		EC_LOCATIONS loc			ON	loc.LOCATION_CODE = emp.HOME_LOCATION_CODE
JOIN		EC_CODE_CONTRACT_CODE cnt	ON	cnt.CODE_VALUE = emp.CONTRACT_CODE
LEFT JOIN	EC_CODE_TERMINATION_CODE t	ON	t.CODE_VALUE = emp.TERMINATION_CODE
LEFT JOIN	EC_CODE_TERMINATION_CODE pt	ON	pt.CODE_VALUE = emp.PREVIOUS_TERMINATION_CODE

